import type { ClubFeed, LiveFixture, LiveResult, ParticipationEntry } from '../types';
import { isRowRestricted } from './compliance';

// Feed dates are plain "YYYY-MM-DD" strings. Every window/selection decision below
// works on those strings or on UTC-parsed parts, never on a local-time Date — a
// local Date shifts the day for anyone east of UTC and silently moves a Sunday
// fixture into the wrong week.

const DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MONTH_NAMES = [
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
];

/** Treat a feed as stale once its `generated` stamp is older than this. */
const STALE_AFTER_HOURS = 36;

/**
 * How long after kick-off a fixture is taken to have been played. Grassroots
 * matches run about an hour; the margin keeps a game keeping kick-off later
 * today from being reported as though it had already happened.
 */
const KICK_OFF_GRACE_MS = 2 * 60 * 60 * 1000;

/** X/Twitter's hard limit — the social variant is trimmed to fit it. */
export const SOCIAL_LIMIT = 280;

/** X shortens every URL to this many weighted characters. */
const X_URL_LENGTH = 23;

/** Unicode ranges that X counts as one unit; all other code points count as two. */
const X_SINGLE_WEIGHT_RANGES: ReadonlyArray<readonly [number, number]> = [
  [0, 4351],
  [8192, 8205],
  [8208, 8223],
  [8242, 8247],
];

function xCharacterLength(text: string): number {
  let length = 0;
  for (const character of text) {
    const codePoint = character.codePointAt(0)!;
    length += X_SINGLE_WEIGHT_RANGES.some(
      ([start, end]) => codePoint >= start && codePoint <= end,
    ) ? 1 : 2;
  }
  return length;
}

/** Count the weighted units X applies to the text generated by this module. */
export function xWeightedLength(text: string): number {
  const normalized = text.normalize();
  const urlPattern = /https?:\/\/\S+/giu;
  let length = 0;
  let previousEnd = 0;

  for (const match of normalized.matchAll(urlPattern)) {
    const start = match.index;
    length += xCharacterLength(normalized.slice(previousEnd, start));
    length += X_URL_LENGTH;
    previousEnd = start + match[0].length;
  }

  return length + xCharacterLength(normalized.slice(previousEnd));
}

export interface RoundupResultLine {
  kind: 'result';
  id: string;
  date: string;
  time: string;
  team: string;
  opponent: string;
  homeAway: 'home' | 'away';
  goalsFor: number;
  goalsAgainst: number;
  outcome: 'W' | 'D' | 'L';
  division: string;
}

/**
 * Two teams from the same club playing each other. The club feed holds the match
 * twice — once from each side — so it is rendered once, neutrally, with no outcome.
 */
export interface RoundupDerbyLine {
  kind: 'derby';
  id: string;
  date: string;
  time: string;
  homeTeam: string;
  awayTeam: string;
  homeScore: number;
  awayScore: number;
  division: string;
}

/**
 * Why a played match has no score.
 *
 * `friendly` — the competition is a friendly, so nobody records a result.
 * `withheld` — redacted for a reason the feed doesn't explain.
 *
 * U11-and-below matches never reach here: they become participation lines
 * before a reason is asked for.
 */
export type UnscoredReason = 'friendly' | 'withheld';

/**
 * A match that was played but carries no score.
 *
 * These are never "results still to come": the scraper drops a results row
 * outright when Full-Time shows no score element at all (postponed, not yet
 * played), and only emits null scores when the page literally prints "X - X"
 * — the league deliberately withholding the score.
 */
export interface RoundupUnscoredLine {
  kind: 'unscored';
  id: string;
  date: string;
  time: string;
  team: string;
  opponent: string;
  homeAway: 'home' | 'away';
  division: string;
  reason: UnscoredReason;
}

/**
 * A U11-and-below match. The FA prohibits publishing results at these ages, and
 * the league's guidance extends that to the opposition and the venue, so this
 * line carries none of them — it says only that the team played, and when.
 *
 * Comes either from the feed's participation array or, where a league never
 * publishes a results row for these ages at all, from a fixture whose kick-off
 * has passed with no result against it.
 */
export interface RoundupParticipationLine {
  kind: 'participation';
  id: string;
  date: string;
  time: string;
  team: string;
  homeAway: 'home' | 'away';
  division: string;
  ageGroup: string | null;
}

/** Every match the club played in the week, scored or not. */
export type RoundupMatch =
  | RoundupResultLine
  | RoundupDerbyLine
  | RoundupUnscoredLine
  | RoundupParticipationLine;

export interface RoundupSummary {
  played: number;
  won: number;
  drawn: number;
  lost: number;
  goalsFor: number;
  goalsAgainst: number;
}

export interface Roundup {
  club: string;
  /** Monday of the roundup week, "YYYY-MM-DD". */
  weekStart: string;
  /** Sunday of the roundup week, "YYYY-MM-DD". */
  weekEnd: string;
  /** One chronological list — scored and unscored together, in kick-off order. */
  matches: RoundupMatch[];
  summary: RoundupSummary;
  generated: string;
  stale: boolean;
}

export interface FormatOptions {
  includeLink?: boolean;
  emoji?: boolean;
  link?: string;
}

export function scoredMatches(roundup: Roundup): (RoundupResultLine | RoundupDerbyLine)[] {
  return roundup.matches.filter(
    (m): m is RoundupResultLine | RoundupDerbyLine =>
      m.kind === 'result' || m.kind === 'derby',
  );
}

export function unscoredMatches(roundup: Roundup): RoundupUnscoredLine[] {
  return roundup.matches.filter((m): m is RoundupUnscoredLine => m.kind === 'unscored');
}

export function participationMatches(roundup: Roundup): RoundupParticipationLine[] {
  return roundup.matches.filter(
    (m): m is RoundupParticipationLine => m.kind === 'participation',
  );
}

/**
 * The roundup with participation games kept or dropped. The summary is rebuilt
 * either way so the record can never describe matches the message doesn't show.
 */
export function withParticipation(roundup: Roundup, include: boolean): Roundup {
  if (include) return roundup;
  const matches = roundup.matches.filter(m => m.kind !== 'participation');
  return { ...roundup, matches, summary: summarise(matches) };
}

// ---------------------------------------------------------------------------
// Dates
// ---------------------------------------------------------------------------

function parseIso(iso: string): Date {
  const [y, m, d] = iso.split('-').map(Number);
  return new Date(Date.UTC(y, m - 1, d));
}

function toIso(date: Date): string {
  return date.toISOString().slice(0, 10);
}

export function addDays(iso: string, days: number): string {
  const date = parseIso(iso);
  date.setUTCDate(date.getUTCDate() + days);
  return toIso(date);
}

/**
 * The Monday of the Mon–Sun week containing `iso`. Grassroots plays Saturday and
 * Sunday, so a Mon–Sun window keeps a whole weekend in one roundup.
 */
export function mondayOf(iso: string): string {
  const date = parseIso(iso);
  const dayOfWeek = date.getUTCDay();
  return addDays(iso, dayOfWeek === 0 ? -6 : 1 - dayOfWeek);
}

/** "Sat 5 Sep" — built by hand so it doesn't drift with locale or timezone. */
export function formatDayShort(iso: string): string {
  const date = parseIso(iso);
  return `${DAY_NAMES[date.getUTCDay()]} ${date.getUTCDate()} ${MONTH_NAMES[date.getUTCMonth()]}`;
}

/** "Sat 5 – Sun 6 Sep", collapsing the repeated month, or a single day. */
export function formatDayRange(startIso: string, endIso: string): string {
  if (startIso === endIso) return formatDayShort(startIso);
  const start = parseIso(startIso);
  const end = parseIso(endIso);
  const startLabel = start.getUTCMonth() === end.getUTCMonth()
    ? `${DAY_NAMES[start.getUTCDay()]} ${start.getUTCDate()}`
    : formatDayShort(startIso);
  return `${startLabel} – ${formatDayShort(endIso)}`;
}

/** Just the weekday: "Sun". */
export function formatWeekday(iso: string): string {
  return DAY_NAMES[parseIso(iso).getUTCDay()];
}

/**
 * A kick-off the way anyone at a ground would say it: "10am", "10:30am", "1pm".
 * Falls back to the raw value if Full-Time gave us something unexpected.
 */
export function formatKickOff(time: string): string {
  const match = /^(\d{1,2}):(\d{2})/.exec(time ?? '');
  if (!match) return time ?? '';
  const hours = Number(match[1]);
  const minutes = Number(match[2]);
  if (hours > 23 || minutes > 59) return time;
  const suffix = hours < 12 ? 'am' : 'pm';
  const hour12 = hours % 12 === 0 ? 12 : hours % 12;
  return minutes === 0 ? `${hour12}${suffix}` : `${hour12}:${match[2]}${suffix}`;
}

/** "Sun 10am" — the prefix every match line opens with. */
export function formatKickOffLabel(date: string, time: string): string {
  return `${formatWeekday(date)} ${formatKickOff(time)}`;
}

// ---------------------------------------------------------------------------
// Selection
// ---------------------------------------------------------------------------

export function getOutcome(result: Pick<LiveResult, 'goals_for' | 'goals_against'>): 'W' | 'D' | 'L' | null {
  if (result.goals_for === null || result.goals_against === null) return null;
  if (result.goals_for > result.goals_against) return 'W';
  if (result.goals_for === result.goals_against) return 'D';
  return 'L';
}

function inWeek(iso: string, weekStart: string): boolean {
  return iso >= weekStart && iso <= addDays(weekStart, 6);
}

/**
 * Strip the club name off the front of a team name — "East Leake Blue U10" reads
 * as "Blue U10" once the club is named in the message header. Falls back to the
 * full name when stripping would leave nothing.
 */
export function stripClubPrefix(teamName: string, clubName: string): string {
  const prefix = clubName.trim();
  if (!prefix) return teamName;
  if (!teamName.toLowerCase().startsWith(`${prefix.toLowerCase()} `)) return teamName;
  return teamName.slice(prefix.length).trim() || teamName;
}

const FRIENDLY_RE = /\bfriendl(?:y|ies)\b/i;

/**
 * Explain a withheld score for a match old enough to have one. Age is not
 * consulted: U11 and below is settled by compliance before this is reached.
 */
export function unscoredReason(row: Pick<LiveResult, 'division'>): UnscoredReason {
  return FRIENDLY_RE.test(row.division) ? 'friendly' : 'withheld';
}

/** Group rows sharing a fixture id — two rows means both sides are this club's. */
function groupById<T extends { id: string }>(rows: T[]): T[][] {
  const groups = new Map<string, T[]>();
  for (const row of rows) {
    const existing = groups.get(row.id);
    if (existing) existing.push(row);
    else groups.set(row.id, [row]);
  }
  return [...groups.values()];
}

function byKickOff(a: { date: string; time: string }, b: { date: string; time: string }): number {
  return a.date.localeCompare(b.date) || a.time.localeCompare(b.time);
}

/**
 * Mondays of every week the club played in, newest first. Participation games
 * count: a club with only U11-and-below teams has no scored results at all, and
 * without them it would be offered no weeks to look at.
 */
export function weeksWithMatches(feed: ClubFeed, now: Date = new Date()): string[] {
  const weeks = new Set<string>();
  const seenIds = new Set<string>();
  for (const result of feed.results) {
    seenIds.add(result.id);
    weeks.add(mondayOf(result.date));
  }
  for (const entry of feed.participation ?? []) {
    if (entry.played === false) continue;
    seenIds.add(entry.id);
    weeks.add(mondayOf(entry.date));
  }
  for (const fixture of feed.fixtures) {
    if (seenIds.has(fixture.id)) continue;
    if (!isRowRestricted(fixture)) continue;
    if (!hasKickedOff(fixture.date, fixture.time, now)) continue;
    weeks.add(mondayOf(fixture.date));
  }
  return [...weeks].sort((a, b) => b.localeCompare(a));
}

/** The week the roundup opens on: the most recent one the club played in. */
export function defaultWeek(feed: ClubFeed): string | null {
  return weeksWithMatches(feed)[0] ?? null;
}

/**
 * Whether a fixture's kick-off is far enough in the past to call it played.
 * Both sides are local wall-clock: a 10am kick-off is 10am where the game is.
 */
function hasKickedOff(date: string, time: string, now: Date): boolean {
  const [year, month, day] = date.split('-').map(Number);
  const [hours, minutes] = (time || '00:00').split(':').map(Number);
  const kickOff = new Date(
    year, month - 1, day,
    Number.isFinite(hours) ? hours : 0,
    Number.isFinite(minutes) ? minutes : 0,
  );
  return now.getTime() - kickOff.getTime() >= KICK_OFF_GRACE_MS;
}

/**
 * Past fixtures with no result recorded, for ages where none ever will be.
 *
 * Some leagues publish no results row whatsoever at U11 and below, so those
 * matches only ever exist as fixtures. Once the kick-off has passed they were
 * played, and belong in the roundup as participation games rather than sitting
 * in the fixture list for ever.
 *
 * Deliberately limited to restricted ages: at open age a fixture with no result
 * is more likely waiting on the league or postponed, and calling it played
 * would assert something we do not know.
 */
function playedWithoutResult(
  fixtures: LiveFixture[],
  weekStart: string,
  seenIds: Set<string>,
  now: Date,
): LiveFixture[] {
  return fixtures.filter(fixture =>
    inWeek(fixture.date, weekStart)
    && !seenIds.has(fixture.id)
    && isRowRestricted(fixture)
    && hasKickedOff(fixture.date, fixture.time, now));
}

function isStale(generated: string): boolean {
  const stamp = Date.parse(generated);
  if (Number.isNaN(stamp)) return false;
  return Date.now() - stamp > STALE_AFTER_HOURS * 60 * 60 * 1000;
}

export function buildRoundup(feed: ClubFeed, weekStart: string, now: Date = new Date()): Roundup {
  const club = feed.club;
  const strip = (name: string) => stripClubPrefix(name, club);
  const matches: RoundupMatch[] = [];
  // Every match id already placed. Fixtures, results and participation entries
  // share one id for the same match (all hashed from date and both team names),
  // so this keeps the three sources from listing it more than once.
  const seenIds = new Set<string>();

  for (const group of groupById(feed.results.filter(r => inWeek(r.date, weekStart)))) {
    const [row] = group;
    seenIds.add(row.id);

    // U11 and below must carry no score, opposition or venue. The feed sends
    // these as participation entries, so this only fires on a stale cached feed
    // or one from a source we do not control. Redact rather than drop: the
    // match still happened.
    if (isRowRestricted(row)) {
      seenIds.add(row.id);
      matches.push(toParticipation({
        id: row.id,
        date: row.date,
        time: row.time,
        team: row.team,
        home_away: row.home_away,
        division: row.division,
        age_group: null,
      }, strip));
      continue;
    }

    if (group.length > 1) {
      // Both sides belong to this club. Use the neutral home/away scores rather
      // than either row's club-side perspective, and award no outcome.
      if (row.home_score === null || row.away_score === null) {
        matches.push(toUnscored(row, strip));
        continue;
      }
      matches.push({
        kind: 'derby',
        id: row.id,
        date: row.date,
        time: row.time,
        homeTeam: strip(row.home_team),
        awayTeam: strip(row.away_team),
        homeScore: row.home_score,
        awayScore: row.away_score,
        division: row.division,
      });
      continue;
    }

    const outcome = getOutcome(row);
    if (outcome === null) {
      matches.push(toUnscored(row, strip));
      continue;
    }
    matches.push({
      kind: 'result',
      id: row.id,
      date: row.date,
      time: row.time,
      team: strip(row.team),
      opponent: row.opponent,
      homeAway: row.home_away,
      goalsFor: row.goals_for as number,
      goalsAgainst: row.goals_against as number,
      outcome,
      division: row.division,
    });
  }

  for (const entry of feed.participation ?? []) {
    if (!inWeek(entry.date, weekStart)) continue;
    // `played: false` marks one still to come; a roundup reports what happened.
    if (entry.played === false) continue;
    if (seenIds.has(entry.id)) continue;
    seenIds.add(entry.id);
    matches.push(toParticipation(entry, strip));
  }

  for (const fixture of playedWithoutResult(feed.fixtures, weekStart, seenIds, now)) {
    seenIds.add(fixture.id);
    matches.push(toParticipation({
      id: fixture.id,
      date: fixture.date,
      time: fixture.time,
      team: fixture.team,
      home_away: fixture.home_away,
      division: fixture.division,
      age_group: null,
    }, strip));
  }

  matches.sort(byKickOff);

  return {
    club,
    weekStart,
    weekEnd: addDays(weekStart, 6),
    matches,
    summary: summarise(matches),
    generated: feed.generated,
    stale: isStale(feed.generated),
  };
}

function toParticipation(
  entry: Pick<ParticipationEntry, 'id' | 'date' | 'time' | 'team' | 'home_away' | 'division'>
    & { age_group?: string | null },
  strip: (name: string) => string,
): RoundupParticipationLine {
  return {
    kind: 'participation',
    id: entry.id,
    date: entry.date,
    time: entry.time,
    team: strip(entry.team),
    homeAway: entry.home_away,
    division: entry.division,
    ageGroup: entry.age_group ?? null,
  };
}

function toUnscored(
  row: LiveResult,
  strip: (name: string) => string,
): RoundupUnscoredLine {
  return {
    kind: 'unscored',
    id: row.id,
    date: row.date,
    time: row.time,
    team: strip(row.team),
    opponent: row.opponent,
    homeAway: row.home_away,
    division: row.division,
    reason: unscoredReason(row),
  };
}

/**
 * Played/W/D/L and goals over the scored, non-derby matches. Derbies are left
 * out on purpose: a club-v-club match is simultaneously a win and a loss for the
 * club, so counting it would make the record say something untrue. Unscored
 * matches have no result to count. Both exclusions keep played === W + D + L.
 */
function summarise(matches: RoundupMatch[]): RoundupSummary {
  const summary: RoundupSummary = {
    played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0,
  };
  for (const match of matches) {
    if (match.kind !== 'result') continue;
    summary.played += 1;
    if (match.outcome === 'W') summary.won += 1;
    else if (match.outcome === 'D') summary.drawn += 1;
    else summary.lost += 1;
    summary.goalsFor += match.goalsFor;
    summary.goalsAgainst += match.goalsAgainst;
  }
  return summary;
}

// ---------------------------------------------------------------------------
// Message composition
// ---------------------------------------------------------------------------

const OUTCOME_EMOJI: Record<'W' | 'D' | 'L', string> = { W: '🟢', D: '🟡', L: '🔴' };
const DERBY_EMOJI = '⚪';
const UNSCORED_EMOJI = '🔵';

/** The span the matches actually cover, which reads better than the full week. */
function matchRange(roundup: Roundup): string {
  const dates = roundup.matches.map(match => match.date).sort();
  if (dates.length === 0) return formatDayRange(roundup.weekStart, roundup.weekEnd);
  return formatDayRange(dates[0], dates[dates.length - 1]);
}

/** The coloured dot that opens a line; a bracketed letter when emoji are off. */
function marker(match: RoundupMatch, emoji: boolean): string {
  if (match.kind === 'result') {
    return emoji ? `${OUTCOME_EMOJI[match.outcome]} ` : `(${match.outcome}) `;
  }
  // A derby and a scoreless match both read unambiguously without emoji — the
  // derby from its neutral scoreline, the others from having no score at all.
  if (match.kind === 'derby') return emoji ? `${DERBY_EMOJI} ` : '';
  return emoji ? `${UNSCORED_EMOJI} ` : '';
}

/** The match itself, without the marker or the kick-off prefix. */
function matchBody(match: RoundupMatch): string {
  if (match.kind === 'result') {
    return `${match.team} ${match.goalsFor}–${match.goalsAgainst} ${match.opponent}`;
  }
  if (match.kind === 'derby') {
    return `${match.homeTeam} ${match.homeScore}–${match.awayScore} ${match.awayTeam}`;
  }
  if (match.kind === 'participation') {
    // Naming the opposition or venue is exactly what the guidance forbids, so
    // the line reports only that this team played, and where they travelled.
    return `${match.team} played ${match.homeAway === 'home' ? 'at home' : 'away'}`;
  }
  const suffix = match.reason === 'friendly' ? ' (friendly)' : '';
  return `${match.team} vs ${match.opponent}${suffix}`;
}

/** "🟢 Sun 10am · Blue U10 4–1 Ruddington Village U10" */
export function matchLine(match: RoundupMatch, emoji: boolean): string {
  return `${marker(match, emoji)}${formatKickOffLabel(match.date, match.time)} · ${matchBody(match)}`;
}

/**
 * One line explaining the blue dots, built only from the reasons actually
 * present so it never claims a cause this week's matches don't have.
 */
function unscoredNote(roundup: Roundup, emoji: boolean): string | null {
  const unscored = unscoredMatches(roundup);
  const participation = participationMatches(roundup);
  if (unscored.length === 0 && participation.length === 0) return null;

  const causes: string[] = [];
  if (participation.length > 0) causes.push('U11 and below');
  if (unscored.some(line => line.reason === 'friendly')) causes.push('friendlies');
  const why = causes.length > 0 ? ` — ${causes.join(', ')}` : '';
  return `${emoji ? `${UNSCORED_EMOJI} ` : ''}No score published${why}`;
}

function summaryLine(summary: RoundupSummary): string {
  const { played, won, drawn, lost, goalsFor, goalsAgainst } = summary;
  return `P${played} · W${won} D${drawn} L${lost} · GF ${goalsFor} GA ${goalsAgainst}`;
}

export function formatWhatsApp(roundup: Roundup, options: FormatOptions = {}): string {
  const { includeLink = true, emoji = true, link = '' } = options;
  const blocks: string[] = [];

  blocks.push(
    `${emoji ? '⚽ ' : ''}${roundup.club} — Weekly Roundup\n${matchRange(roundup)}`,
  );

  if (roundup.matches.length > 0) {
    blocks.push(roundup.matches.map(match => matchLine(match, emoji)).join('\n'));
  } else {
    blocks.push('No results published for this week.');
  }

  if (roundup.summary.played > 0) {
    blocks.push(`${emoji ? '📊 ' : ''}${summaryLine(roundup.summary)}`);
  }

  const note = unscoredNote(roundup, emoji);
  if (note) blocks.push(note);

  if (includeLink && link) blocks.push(`Full results:\n${link}`);

  return blocks.join('\n\n');
}

/** A hashtag from the club name: "East Leake FC" -> "#EastLeakeFC". */
function clubHashtag(club: string): string {
  const words = club.replace(/[^\p{L}\p{N} ]/gu, '').split(/\s+/).filter(Boolean);
  return words.length > 0 ? `#${words.join('')}` : '';
}

export interface SocialMessage {
  text: string;
  length: number;
  /** Lines were dropped to fit SOCIAL_LIMIT. */
  truncated: boolean;
}

/**
 * The social variant has to fit X's 280 characters, so it is composed at
 * decreasing levels of detail and the longest version that fits wins.
 */
export function formatSocial(roundup: Roundup, options: FormatOptions = {}): SocialMessage {
  const { includeLink = true, emoji = true, link = '' } = options;
  const { summary } = roundup;

  const header = `${emoji ? '⚽ ' : ''}${roundup.club} weekend roundup`;
  const record = summary.played > 0 ? `W${summary.won} D${summary.drawn} L${summary.lost}` : '';
  const tags = [clubHashtag(roundup.club), '#GrassrootsFootball'].filter(Boolean).join(' ');
  const tail = includeLink && link ? link : '';

  const compose = (shown: number, withTags: boolean): string => {
    const blocks: string[] = [record ? `${header}\n${record}` : header];

    if (roundup.matches.length === 0) {
      blocks.push('No results published this week.');
    } else {
      const lines = roundup.matches.slice(0, shown).map(match => matchLine(match, emoji));
      const hidden = roundup.matches.length - shown;
      if (hidden > 0) lines.push(`+${hidden} more`);
      blocks.push(lines.join('\n'));
    }

    if (withTags && tags) blocks.push(tags);
    if (tail) blocks.push(tail);
    return blocks.join('\n\n');
  };

  const total = roundup.matches.length;
  for (const withTags of [true, false]) {
    for (let shown = total; shown >= 1; shown--) {
      const text = compose(shown, withTags);
      const length = xWeightedLength(text);
      if (length <= SOCIAL_LIMIT) {
        return { text, length, truncated: shown < total };
      }
    }
  }

  // Nothing fits — hand back the shortest form and let the UI show it over budget.
  const text = compose(1, false);
  return { text, length: xWeightedLength(text), truncated: total > 1 };
}

export function formatEmailSubject(roundup: Roundup): string {
  return `${roundup.club} results — week ending ${formatDayShort(roundup.weekEnd)}`;
}

export function formatEmailBody(roundup: Roundup, options: FormatOptions = {}): string {
  const { includeLink = true, emoji = false, link = '' } = options;
  const blocks: string[] = [];

  blocks.push(`Results, ${matchRange(roundup)}`);

  if (roundup.matches.length > 0) {
    blocks.push(roundup.matches.map(match => `  ${matchLine(match, emoji)}`).join('\n'));
  } else {
    blocks.push('  No results published for this week.');
  }

  if (roundup.summary.played > 0) {
    const { played, won, drawn, lost, goalsFor, goalsAgainst } = roundup.summary;
    blocks.push(
      `Played ${played}  Won ${won}  Drawn ${drawn}  Lost ${lost}\n` +
      `Goals for ${goalsFor}, against ${goalsAgainst}`,
    );
  }

  const note = unscoredNote(roundup, emoji);
  if (note) blocks.push(note);

  if (includeLink && link) blocks.push(`Full results: ${link}`);
  blocks.push('Results from FA Full-Time via touchlineHQ.');

  return blocks.join('\n\n');
}
